# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/sync-labels/universal.yml
# See: https://github.com/Financial-Times/github-label-sync#label-config-file
# Maximum lengths:
# name: 50
# description: 100

- name: "conclusion: declined"
  color: "940404"
  description: Will not be worked on
  aliases:
    - wontfix
- name: "conclusion: duplicate"
  color: "ff0000"
  description: Has already been submitted
  aliases:
    - duplicate
- name: "conclusion: invalid"
  color: "ff0000"
  description: Issue/PR not valid
  aliases:
    - invalid
- name: "conclusion: off topic"
  color: "ff0000"
  description: Off topic for this repository
# For use when it's not possible to do a true transfer
# (PRs, different organizations, or maintainer doesn't have write permissions in target repo).
- name: "conclusion: moved"
  color: "940404"
  description: Issue/PR moved to another repository
- name: "conclusion: resolved"
  color: "00ff00"
  description: Issue was resolved
- name: "criticality: highest"
  color: "ff0000"
  description: Of highest impact
- name: "criticality: high"
  color: "ffa200"
  description: Of high impact
- name: "criticality: medium"
  color: "ffff00"
  description: Of moderate impact
- name: "criticality: low"
  color: "c0c0c0"
  description: Of low impact
# Distinct from the criticality labels in that priority is assigned based on estimated effort in addition to impact.
- name: "priority: high"
  color: "ffa200"
  description: Resolution is a high priority
- name: "priority: medium"
  color: "ffff00"
  description: Resolution is a medium priority
- name: "priority: low"
  color: "c0c0c0"
  description: Resolution is a low priority
- name: "status: changes requested"
  color: "ffa200"
  description: Changes to PR are required before merge
- name: "status: in progress"
  color: "0000ff"
  description: Work is in progress on this
- name: "status: on hold"
  color: "940404"
  description: Do not proceed at this time
- name: "status: waiting for information"
  color: "ffff00"
  aliases:
    - Waiting for feedback
    - waiting for feedback
  description: More information must be provided before work can proceed
- name: "status: blocked"
  color: "940404"
  description: Progress on this prevented by an external cause
# Ideally this would be "status: help wanted", but GitHub gives this label special treatment so it's best to leave it
# stock.
- name: help wanted
  color: "ffa200"
  description: Assistance from the community is especially welcome
- name: "topic: infrastructure"
  color: "00ffff"
  description: Related to project infrastructure
  aliases:
    - dependencies
- name: "topic: code"
  color: "00ffff"
  description: Related to content of the project itself
- name: "topic: documentation"
  color: "00ffff"
  description: Related to documentation for the project
  aliases:
    - documentation
# This includes bugs, but avoids confusion for use in non-code contexts.
- name: "type: imperfection"
  color: "ff0000"
  description: Perceived defect in any part of project
  aliases:
    - bug
- name: "type: enhancement"
  color: "008000"
  description: Proposed improvement
  aliases:
    - enhancement
# All support request issues must be closed as "conclusion: invalid", redirecting the user to the Arduino forum, but
# it's still useful to label the closed issues and this type doesn't fit into the imperfection/enhancement dichotomy.
- name: "type: support"
  color: "ff0000"
  description: "OT: Request for help using the project"
  aliases:
    - question
